version: '3'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - ../../postgresql/data:/var/lib/postgresql/data/
    ports:
      - "5434:5432"
    env_file:
      - ./deploy/envs/db.env

  app:
    build:
      dockerfile: Dockerfile
      context: app
#    command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
      - ./static:/usr/src/app/static
#    ports:
#      - "8000:8000"
    expose:
      - 8000
    env_file:
      - ./deploy/envs/app.env
    entrypoint: ./app/entrypoint.sh
    depends_on:
      - db

  nginx:
    build:
      dockerfile: Dockerfile
      context: nginx
    image: nginx:1.19.2
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/static
    ports:
      - "1337:8000"
    depends_on:
      - app
