# Generated by Django 3.2 on 2022-04-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personfilmwork',
            name='role',
            field=models.TextField(choices=[('director', 'director'), ('writer', 'writer'), ('actor', 'actor')], default='actor', max_length=10, verbose_name='role'),
        ),
    ]
